@extends('layouts.app')
@section('content')
	<h2>Ficha Prenatal de {{ $paciente->nombres }} {{ $paciente->apellidos }} </h2>
           <p>{{ $data->gesta }} </p>
           <p>{{ $data->aborto }} </p>
           <p>{{ $data->vaginales }} </p>
           <p>{{ $data->vivos }} </p>
           <p>{{ $data->viven }} </p>
           <p>{{ $data->semana1 }} </p>
           <p>{{ $data->semana2 }} </p>
           <p>{{ $data->cesaria }} </p>
           <p>{{ $data->parto }} </p>
           <p>{{ $data->num }} </p>
           <p>{{ $data->gr }} </p>
           <p>{{ $data->gemelar }} </p>
           <p>{{ $data->m37m }} </p>
           <p>{{ $data->fecha_terminacion }} </p>
           <p>{{ $data->peso_gestacion }} </p>
           <p>{{ $data->ninguno_af }} </p>
           <p>{{ $data->alergias_af }} </p>
           <p>{{ $data->anomalias_af }} </p>
           <p>{{ $data->epilepsia_af }} </p>
           <p>{{ $data->diabetes_af }} </p>
           <p>{{ $data->enfermedades_af }} </p>
           <p>{{ $data->gemelares_af }} </p>
           <p>{{ $data->tension_af }} </p>
           <p>{{ $data->neoplasia_af }} </p>
           <p>{{ $data->pulmon_af }} </p>
           <p>{{ $data->otro_af }} </p>
           <p>{{ $data->ninguno_ap }} </p>
           <p>{{ $data->aborto_ap }} </p>
           <p>{{ $data->aborto2_ap }} </p>
           <p>{{ $data->alcohol_ap }} </p>
           <p>{{ $data->alermedicamentos_ap }} </p>
           <p>{{ $data->asmabron_ap }} </p>
           <p>{{ $data->pesonacimiento_ap }} </p>
           <p>{{ $data->cardiopatia_ap }} </p>
           <p>{{ $data->cirugiauterina_ap }} </p>
           <p>{{ $data->diabetes_ap }} </p>
           <p>{{ $data->congenitas_ap }} </p>
           <p>{{ $data->infeccion_ap }} </p>
           <p>{{ $data->epilepsia_ap }} </p>
           <p>{{ $data->hemorragiapost_ap }} </p>
           <p>{{ $data->htarterial_ap }} </p>
           <p>{{ $data->coca_ap }} </p>
           <p>{{ $data->infertilidad_ap }} </p>
           <p>{{ $data->neoplasias_ap }} </p>
           <p>{{ $data->drogas_ap }} </p>
           <p>{{ $data->partoprolongado_ap }} </p>
           <p>{{ $data->eclampsia_ap }} </p>
           <p>{{ $data->prematuro_ap }} </p>
           <p>{{ $data->placenta_ap }} </p>
           <p>{{ $data->tabaco_ap }} </p>
           <p>{{ $data->pulmonar_ap }} </p>
           <p>{{ $data->sida_ap }} </p>
           <p>{{ $data->otro_ap }} </p>
           <p>{{ $data->peso_pregestacional }} </p>
           <p>{{ $data->talla_pregestacional }} </p>
           <p>{{ $data->dosis_previa }} </p>
           <p>{{ $data->primera_dosis }} </p>
           <p>{{ $data->segunda_dosis }} </p>
           <p>{{ $data->sesion_sangre }} </p>
           <p>{{ $data->ultima_menstruacion }} </p>
           <p>{{ $data->parto_probable }} </p>
           <p>{{ $data->eco_eg }} </p>
           <p>{{ $data->serologia_1era }} </p>
           <p>{{ $data->serologia_2da }} </p>
           <p>{{ $data->hemoglobina }} </p>
           <p>{{ $data->hemoglobina_fecha }} </p>
           <p>{{ $data->patologia_1 }} </p>
           <p>{{ $data->patologia_1_date }} </p>
           <p>{{ $data->patologia_1_otro }} </p>
           <p>{{ $data->patologia_2 }} </p>
           <p>{{ $data->patologia_2_date }} </p>
           <p>{{ $data->patologia_2_otro }} </p>
           <p>{{ $data->patologia_3 }} </p>
           <p>{{ $data->patologia_3_date }} </p>
           <p>{{ $data->patologia_3_otro }} </p>
           <p>{{ $data->talla_nacido }} </p>
           <p>{{ $data->peso_nacido }} </p>
           <p>{{ $data->cef_nacido }} </p>
           <p>{{ $data->temp_nacido }} </p>
           <p>{{ $data->no_rn }} </p>
           <p>{{ $data->nombre_rn }} </p>
           <p>{{ $data->edad_semanas }} </p>
           <p>{{ $data->apgar_1 }} </p>
           <p>{{ $data->apgar_2 }} </p>
           <p>{{ $data->patologia_recien_1 }} </p>
           <p>{{ $data->patologia_recien_1_date }} </p>
           <p>{{ $data->patologia_recien_2 }} </p>
           <p>{{ $data->patologia_recien_2_date }} </p>
           <p>{{ $data->patologia_recien_3 }} </p>
           <p>{{ $data->patologia_recien_3_date }} </p>
           <p>{{ $data->otros_cie1_10 }} </p>
           <p>{{ $data->otros_cie2_10 }} </p>
@endsection